---
domain: api
descriptors:
- key: remote_address
  rate_limit:
    unit: minute
    requests_per_unit: 15

- key: remote_address
  value: 127.0.0.1
  rate_limit:
    unit: minute
    requests_per_unit: 50
