---
domain: api

descriptors:
- key: header_match
  value: cf-ip-missing
  rate_limit:
    unit: second
    requests_per_unit: 0

# Blacklisted IP Address.
- key: cf-ip-address
  value: "0.0.0.0"
  rate_limit:
    unit: minute
    requests_per_unit: 0

# Whitelisted IP Address.
- key: cf-ip-address
  value: "163.172.165.12"
  rate_limit:
    unit: minute
    requests_per_unit: 5

# Common IP Address.
- key: cf-ip-address
  rate_limit:
    unit: minute
    requests_per_unit: 2
